stages:
  - validate
  - plan
  - apply

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform

validate:
  stage: validate
  script:
    - terraform validate
  except:
    refs:
      - master

plan:
  stage: plan
  script:
    - terraform plan --out plan
  needs:
    - job: validate
  only:
    refs:
      - master
  artifacts:
    paths:
      - plan
  environment:
    name: blog_production

apply:
  stage: apply
  script:
    - terraform apply --auto-approve plan
  when: manual
  allow_failure: false
  needs:
    - job: plan
  only:
    refs:
      - master
  environment:
    name: blog_production
