include:
  - template: Terraform/Base.latest.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - deploy

init:
  extends: .init

validate:
  extends: .validate
  needs:
    - job: init

build_blog_prod:
  extends: .build
  script:
    - apk update
    - apk add bash py-pip
    - apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python-dev
    - pip install azure-cli
    - apk del --purge build
    - curl -L https://aka.ms/InstallAzureCli | bash
    - az login --service-principal --username="${AZURE_APP_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant=${TF_VAR_tenant_id}
  needs:
    - job: validate
  environment:
    name: blog_production

deploy_blog_prod:
  extends: .deploy
  script:
    - apk update
    - apk add bash py-pip
    - apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python-dev
    - pip install azure-cli
    - apk del --purge build
    - curl -L https://aka.ms/InstallAzureCli | bash
    - az login --service-principal --username="${AZURE_APP_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant=${TF_VAR_tenant_id}
  needs:
    - job: build_blog_prod
  environment:
    name: blog_production
