include:
  - template: Terraform/Base.latest.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - deploy

init:
  extends: .init

validate:
  extends: .validate

build_blog_prod:
  extends: .build
  environment:
    name: blog_production

deploy_blog_prod:
  extends: .deploy
  dependencies:
    - build_blog_prod
  environment:
    name: blog_production
